import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'staff',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'role', type: 'string' },
        { name: 'pin', type: 'string' },
        { name: 'phone', type: 'string' },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'devices',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'device_fingerprint', type: 'string' },
        { name: 'is_approved', type: 'boolean' },
        { name: 'registered_at', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'categories',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'prep_station', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'products',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'category_id', type: 'string', isIndexed: true },
        { name: 'price', type: 'number' },
        { name: 'cost_price', type: 'number' },
        { name: 'stock_qty', type: 'number' },
        { name: 'unit', type: 'string' },
        { name: 'low_stock_threshold', type: 'number' },
        { name: 'low_stock_alert_sent', type: 'boolean' },
        { name: 'is_out_of_stock', type: 'boolean' },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'stock_adjustments',
      columns: [
        { name: 'product_id', type: 'string', isIndexed: true },
        { name: 'adjusted_by', type: 'string' },
        { name: 'change_qty', type: 'number' },
        { name: 'reason', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'restaurant_tables',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'orders',
      columns: [
        { name: 'table_id', type: 'string', isIndexed: true },
        { name: 'staff_id', type: 'string', isIndexed: true },
        { name: 'shift_id', type: 'string', isIndexed: true },
        { name: 'device_id', type: 'string' },
        { name: 'customer_id', type: 'string', isOptional: true },
        { name: 'is_credit', type: 'boolean' },
        { name: 'room_number', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'opened_at', type: 'number' },
        { name: 'closed_at', type: 'number', isOptional: true },
        { name: 'discount_amount', type: 'number' },
        { name: 'discount_reason', type: 'string', isOptional: true },
        { name: 'total_amount', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'order_items',
      columns: [
        { name: 'order_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isIndexed: true },
        { name: 'qty', type: 'number' },
        { name: 'unit_price', type: 'number' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'is_complimentary', type: 'boolean' },
        { name: 'comp_reason', type: 'string', isOptional: true },
        { name: 'comp_authorized_by', type: 'string', isOptional: true },
        { name: 'voided', type: 'boolean' },
        { name: 'void_reason', type: 'string', isOptional: true },
        { name: 'voided_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'payments',
      columns: [
        { name: 'order_id', type: 'string', isIndexed: true },
        { name: 'method', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'mpesa_ref', type: 'string', isOptional: true },
        { name: 'paid_at', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'refunds',
      columns: [
        { name: 'payment_id', type: 'string', isIndexed: true },
        { name: 'amount', type: 'number' },
        { name: 'reason', type: 'string' },
        { name: 'authorized_by', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'customers',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'credit_limit', type: 'number' },
        { name: 'is_active', type: 'boolean' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_by', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'credit_transactions',
      columns: [
        { name: 'customer_id', type: 'string', isIndexed: true },
        { name: 'order_id', type: 'string', isOptional: true },
        { name: 'type', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'payment_method', type: 'string', isOptional: true },
        { name: 'mpesa_ref', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'recorded_by', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'expense_categories',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'expenses',
      columns: [
        { name: 'category_id', type: 'string', isIndexed: true },
        { name: 'description', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'paid_by', type: 'string' },
        { name: 'logged_by', type: 'string' },
        { name: 'date', type: 'string' },
        { name: 'receipt_photo_url', type: 'string', isOptional: true },
        { name: 'source', type: 'string' },
        { name: 'vendor_name', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'shifts',
      columns: [
        { name: 'staff_id', type: 'string', isIndexed: true },
        { name: 'opened_at', type: 'number' },
        { name: 'closed_at', type: 'number', isOptional: true },
        { name: 'opening_cash', type: 'number' },
        { name: 'closing_cash_expected', type: 'number', isOptional: true },
        { name: 'closing_cash_actual', type: 'number', isOptional: true },
        { name: 'variance', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'audit_log',
      columns: [
        { name: 'action', type: 'string' },
        { name: 'entity_type', type: 'string' },
        { name: 'entity_id', type: 'string' },
        { name: 'staff_id', type: 'string' },
        { name: 'device_id', type: 'string' },
        { name: 'details', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
